<?php
/*
 * FreteasyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FreteasyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Address implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $postcode public property
     */
    public $postcode;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $postcode Initialization value for $this->postcode
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->postcode = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['postcode'] = $this->postcode;

        return $json;
    }
}
