<?php
/*
 * FreteasyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FreteasyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Dimensions implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $width public property
     */
    public $width;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $height public property
     */
    public $height;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $length public property
     */
    public $length;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $diameter public property
     */
    public $diameter;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $width    Initialization value for $this->width
     * @param string $height   Initialization value for $this->height
     * @param string $length   Initialization value for $this->length
     * @param string $diameter Initialization value for $this->diameter
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->width    = func_get_arg(0);
            $this->height   = func_get_arg(1);
            $this->length   = func_get_arg(2);
            $this->diameter = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['width']    = $this->width;
        $json['height']   = $this->height;
        $json['length']   = $this->length;
        $json['diameter'] = $this->diameter;

        return $json;
    }
}
