<?php
/*
 * FreteasyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FreteasyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Quote1 implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var \FreteasyLib\Models\Product[] $products public property
     */
    public $products;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $products Initialization value for $this->products
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->products = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['products'] = $this->products;

        return $json;
    }
}
