<?php
/*
 * FreteasyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FreteasyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Quote implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var \FreteasyLib\Models\Service[] $services public property
     */
    public $services;

    /**
     * @todo Write general description for this property
     * @required
     * @var \FreteasyLib\Models\Sender $sender public property
     */
    public $sender;

    /**
     * @todo Write general description for this property
     * @required
     * @var \FreteasyLib\Models\Destiny $destiny public property
     */
    public $destiny;

    /**
     * @todo Write general description for this property
     * @required
     * @var \FreteasyLib\Models\Quote1 $quote public property
     */
    public $quote;

    /**
     * Constructor to set initial or default values of member properties
     * @param array   $services Initialization value for $this->services
     * @param Sender  $sender   Initialization value for $this->sender
     * @param Destiny $destiny  Initialization value for $this->destiny
     * @param Quote1  $quote    Initialization value for $this->quote
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->services = func_get_arg(0);
            $this->sender   = func_get_arg(1);
            $this->destiny  = func_get_arg(2);
            $this->quote    = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['services'] = $this->services;
        $json['sender']   = $this->sender;
        $json['destiny']  = $this->destiny;
        $json['quote']    = $this->quote;

        return $json;
    }
}
