<?php
/*
 * FreteasyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FreteasyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Sender implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $codCompany public property
     */
    public $codCompany;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $county public property
     */
    public $county;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $state public property
     */
    public $state;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $postcode public property
     */
    public $postcode;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $codCompany Initialization value for $this->codCompany
     * @param string $county     Initialization value for $this->county
     * @param string $state      Initialization value for $this->state
     * @param string $postcode   Initialization value for $this->postcode
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->codCompany = func_get_arg(0);
            $this->county     = func_get_arg(1);
            $this->state      = func_get_arg(2);
            $this->postcode   = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['codCompany'] = $this->codCompany;
        $json['county']     = $this->county;
        $json['state']      = $this->state;
        $json['postcode']   = $this->postcode;

        return $json;
    }
}
