<?php
/*
 * FreteasyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FreteasyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Service implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @var string|null $key public property
     */
    public $key;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $token public property
     */
    public $token;

    /**
     * @todo Write general description for this property
     * @var \FreteasyLib\Models\Param[]|null $params public property
     */
    public $params;

    /**
     * @todo Write general description for this property
     * @var string|null $code public property
     */
    public $code;

    /**
     * @todo Write general description for this property
     * @var string|null $account public property
     */
    public $account;

    /**
     * @todo Write general description for this property
     * @var string|null $contract public property
     */
    public $contract;

    /**
     * @todo Write general description for this property
     * @var string|null $secureType public property
     */
    public $secureType;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $id         Initialization value for $this->id
     * @param string $key        Initialization value for $this->key
     * @param string $token      Initialization value for $this->token
     * @param array  $params     Initialization value for $this->params
     * @param string $code       Initialization value for $this->code
     * @param string $account    Initialization value for $this->account
     * @param string $contract   Initialization value for $this->contract
     * @param string $secureType Initialization value for $this->secureType
     */
    public function __construct()
    {
        if (8 == func_num_args()) {
            $this->id         = func_get_arg(0);
            $this->key        = func_get_arg(1);
            $this->token      = func_get_arg(2);
            $this->params     = func_get_arg(3);
            $this->code       = func_get_arg(4);
            $this->account    = func_get_arg(5);
            $this->contract   = func_get_arg(6);
            $this->secureType = func_get_arg(7);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']         = $this->id;
        $json['key']        = $this->key;
        $json['token']      = $this->token;
        $json['params']     = $this->params;
        $json['code']       = $this->code;
        $json['account']    = $this->account;
        $json['contract']   = $this->contract;
        $json['secureType'] = $this->secureType;

        return $json;
    }
}
